return {
	"catppuccin/nvim",
	name = "catppuccin",
	lazy = false,
	priority = 1000,
	config = function()
		require("catppuccin").setup({
			background = {
				light = "latte",
				dark = "mocha",
			},
			no_italic = true,
			transparent_background = true,
			show_end_of_buffer = false,
			integration_default = false,
			styles = {
				-- keywords = { "bold" },
				-- loops = { "bold" },
				-- operators = { "bold" },
				-- conditionals = { "bold" },
			},
			integrations = {
				barbecue = { dim_dirname = true, bold_basename = true, dim_context = false, alt_background = false },
				cmp = true,
				gitsigns = true,
				illuminate = { enabled = true },
				markdown = true,
				mason = true,
				native_lsp = { enabled = true, inlay_hints = { background = true } },
				neogit = true,
				neotree = true,
				semantic_tokens = true,
				treesitter = true,
				treesitter_context = true,
				vimwiki = true,
				which_key = true,
			},
			color_overrides = {
				mocha = {
					-- gruvbox-material
					-- rosewater = "#ea6962",
					-- flamingo = "#ea6962",
					-- red = "#ea6962",
					-- maroon = "#ea6962",
					-- pink = "#d3869b",
					-- mauve = "#d3869b",
					-- peach = "#e78a4e",
					-- yellow = "#d8a657",
					-- green = "#a9b665",
					-- teal = "#89b482",
					-- sky = "#89b482",
					-- sapphire = "#89b482",
					-- blue = "#7daea3",
					-- lavender = "#7daea3",
					-- text = "#ebdbb2",
					-- subtext1 = "#d5c4a1",
					-- subtext0 = "#bdae93",
					-- overlay2 = "#a89984",
					-- overlay1 = "#928374",
					-- overlay0 = "#595959",
					-- surface2 = "#4d4d4d",
					-- surface1 = "#404040",
					-- surface0 = "#292929",
					-- base = "#1d2021",
					-- mantle = "#191b1c",
					-- crust = "#141617",

					-- rosewater = "#ff7f66",
					-- flamingo = "#ff7f66",
					-- red = "#ff7f66",
					-- maroon = "#ff7f66",
					-- pink = "#df879e",
					-- mauve = "#df879e",
					-- peach = "#fca965",
					-- yellow = "#e0ae6a",
					-- green = "#a5c977",
					-- teal = "#88b992",
					-- sky = "#88b992",
					-- sapphire = "#88b992",
					-- blue = "#72bfb8",
					-- lavender = "#72bfb8",
					-- text = "#eae3d5",
					-- subtext1 = "#d5c9b7",
					-- subtext0 = "#bfb3a5",
					-- overlay2 = "#aca195",
					-- overlay1 = "#958b7e",
					-- overlay0 = "#6f6660",
					-- surface2 = "#585858",
					-- surface1 = "#4b4b4b",
					-- surface0 = "#353535",
					-- -- base = "#21262d",
					-- -- base = "#292e2f",
					-- base = "#1d2021",
					-- mantle = "#1d2021",
					-- -- mantle = "#292e2f",
					-- crust = "#1d2021",
					-- -- crust = "#292e2f",

					-- rosewater = "#ffffff",
					-- flamingo = "#ffffff",
					-- red = "#ffdd33",
					-- maroon = "#ffffff",
					-- pink = "#ffdd33",
					-- mauve = "#ffdd33",
					-- peach = "#96a6c8",
					-- yellow = "#95a99f",
					-- green = "#73c936",
					-- teal = "#88b992",
					-- sky = "#cc8c3c",
					-- sapphire = "#96a6c8",
					-- blue = "#778899",
					-- lavender = "#778899",
					-- text = "#ffffff",
					-- subtext1 = "#d5c9b7",
					-- subtext0 = "#bfb3a5",
					-- overlay2 = "#aca195",
					-- overlay1 = "#958b7e",
					-- overlay0 = "#6f6660",
					-- surface2 = "#585858",
					-- surface1 = "#4b4b4b",
					-- surface0 = "#353535",
					-- base = "#181818",
					-- mantle = "#181818",
					-- crust = "#181818",

					-- gruber-darker
					-- rosewater = "#ffffff",
					-- flamingo = "#ffffff",
					-- red = "#ffdd33",
					-- maroon = "#ffffff",
					-- pink = "#ffdd33",
					-- mauve = "#ffdd33",
					-- peach = "#96a6c8",
					-- yellow = "#95a99f",
					-- green = "#73c936",
					-- teal = "#88b992",
					-- sky = "#cc8c3c",
					-- sapphire = "#96a6c8",
					-- blue = "#778899",
					-- lavender = "#ffffff",
					-- text = "#ffffff",
					-- subtext1 = "#d5c9b7",
					-- subtext0 = "#bfb3a5",
					-- overlay2 = "#aca195",
					-- overlay1 = "#958b7e",
					-- overlay0 = "#6f6660",
					-- surface2 = "#585858",
					-- surface1 = "#4b4b4b",
					-- surface0 = "#353535",
					-- base = "#181818",
					-- mantle = "#181818",
					-- crust = "#181818",
					--

					-- aquarium
					-- rosewater = "#e8e8d3",
					-- flamingo = "#e8e8d3",
					-- red = "#ffeb99",
					-- maroon = "#e8e8d3",
					-- pink = "#bbdaff",
					mauve = "#ff9da4",
					-- mauve = "#8BCCBF",
					-- peach = "#bbdaff",
					-- yellow = "#e0b0e3",
					-- green = "#cae187",
					-- teal = "#88b992",
					-- sky = "#ff9da4",
					-- sapphire = "#96a6c8",
					-- -- blue = "#bbdaff",
					-- blue = "#eebbb6",
					-- lavender = "#FFDAB9",
					-- text = "#eae3d5",
					-- subtext1 = "#d5c9b7",
					-- subtext0 = "#bfb3a5",
					-- overlay2 = "#aca195",
					-- overlay1 = "#958b7e",
					-- overlay0 = "#6f6660",
					-- surface2 = "#585858",
					-- surface1 = "#4b4b4b",
					-- surface0 = "#353535",
					-- base = "#151515",
					-- mantle = "#1d2021",
					-- crust = "#1d2021",
					--
					-- falcon
					-- rosewater = "#e8e8d3",
					-- flamingo = "#e8e8d3",
					-- red = "#a1bce1",
					-- maroon = "#e8e8d3",
					-- pink = "#bbdaff",
					-- mauve = "#8BCCBF",
					-- peach = "#BFDAFF",
					-- yellow = "#FFB07B",
					-- green = "#cae187",
					-- teal = "#88b992",
					-- sky = "#FF761A",
					-- sapphire = "#96a6c8",
					-- blue = "#FFC552",
					-- lavender = "#ffffff",
					-- text = "#ffffff",
					-- subtext1 = "#d5c9b7",
					-- subtext0 = "#bfb3a5",
					-- overlay2 = "#aca195",
					-- overlay1 = "#958b7e",
					-- overlay0 = "#6f6660",
					-- surface2 = "#585858",
					-- surface1 = "#4b4b4b",
					-- surface0 = "#353535",
					-- -- base = "#151515",
					-- base = "#1d2021",
					-- mantle = "#1d2021",
					-- crust = "#1d2021",
					-- falcon 2
					-- rosewater = "#e8e8d3",
					-- flamingo = "#e8e8d3",
					-- red = "#d8d8a6",
					-- maroon = "#e8e8d3",
					-- pink = "#bbdaff",
					-- mauve = "#bc80b7",
					-- peach = "#BFDAFF",
					-- yellow = "#FFB07B",
					-- green = "#cae187",
					-- teal = "#88b992",
					-- sky = "#FF761A",
					-- sapphire = "#96a6c8",
					-- blue = "#FFC552",
					-- lavender = "#ffffff",
					-- text = "#ffffff",
					-- subtext1 = "#d5c9b7",
					-- subtext0 = "#bfb3a5",
					-- overlay2 = "#aca195",
					-- overlay1 = "#958b7e",
					-- overlay0 = "#6f6660",
					-- surface2 = "#585858",
					-- surface1 = "#4b4b4b",
					-- surface0 = "#353535",
					-- -- base = "#151515",
					-- base = "#1E1E1E",
					-- mantle = "#1d2021",
					-- crust = "#1d2021",

					-- ayu
					-- rosewater = "#F5B8AB",
					-- flamingo = "#F29D9D",
					-- pink = "#AD6FF7",
					-- mauve = "#FF8F40",
					-- red = "#E66767",
					-- maroon = "#EB788B",
					peach = "#FAB770",
					-- yellow = "#FACA64",
					-- green = "#70CF67",
					-- teal = "#4CD4BD",
					-- sky = "#61BDFF",
					-- sapphire = "#4BA8FA",
					-- blue = "#00BFFF",
					-- lavender = "#00BBCC",
					-- text = "#C1C9E6",
					-- subtext1 = "#A3AAC2",
					-- subtext0 = "#8E94AB",
					-- overlay2 = "#7D8296",
					-- overlay1 = "#676B80",
					-- overlay0 = "#464957",
					-- surface2 = "#3A3D4A",
					-- surface1 = "#2F313D",
					-- surface0 = "#1D1E29",
					-- base = "#0b0b12",
					-- mantle = "#11111a",
					-- crust = "#191926",
				},
				macchiato = {
					-- rosewater = "#F5B8AB",
					-- flamingo = "#F29D9D",
					-- pink = "#AD6FF7",
					-- mauve = "#FF8F40",
					-- red = "#E66767",
					-- maroon = "#EB788B",
					-- peach = "#FAB770",
					-- yellow = "#FACA64",
					-- green = "#70CF67",
					-- teal = "#4CD4BD",
					-- sky = "#61BDFF",
					-- sapphire = "#4BA8FA",
					-- blue = "#00BFFF",
					-- lavender = "#00BBCC",
					-- text = "#C1C9E6",
					-- subtext1 = "#A3AAC2",
					-- subtext0 = "#8E94AB",
					-- overlay2 = "#7D8296",
					-- overlay1 = "#676B80",
					-- overlay0 = "#464957",
					-- surface2 = "#3A3D4A",
					-- surface1 = "#2F313D",
					-- surface0 = "#1D1E29",
					-- base = "#0b0b12",
					-- mantle = "#11111a",
					-- crust = "#191926",
				},
			},
			-- highlight_overrides = {
			--   all = function(colors)
			--     return {
			--       CurSearch = { bg = colors.sky },
			--       IncSearch = { bg = colors.sky },
			--       DashboardFooter = { fg = colors.overlay0 },
			--       TreesitterContextBottom = { style = {} },
			--       -- ["@markup.italic"] = { fg = colors.blue, style = { "italic" } },
			--       ["@markup.strong"] = { fg = colors.blue, style = { "bold" } },
			--       Headline = { style = { "bold" } },
			--       Headline1 = { fg = colors.blue, style = { "bold" } },
			--       Headline2 = { fg = colors.pink, style = { "bold" } },
			--       Headline3 = { fg = colors.lavender, style = { "bold" } },
			--       Headline4 = { fg = colors.green, style = { "bold" } },
			--       Headline5 = { fg = colors.peach, style = { "bold" } },
			--       Headline6 = { fg = colors.flamingo, style = { "bold" } },
			--       rainbow1 = { fg = colors.blue, style = { "bold" } },
			--       rainbow2 = { fg = colors.pink, style = { "bold" } },
			--       rainbow3 = { fg = colors.lavender, style = { "bold" } },
			--       rainbow4 = { fg = colors.green, style = { "bold" } },
			--       rainbow5 = { fg = colors.peach, style = { "bold" } },
			--       rainbow6 = { fg = colors.flamingo, style = { "bold" } },
			--
			--
			--       NormalFloat = { bg = colors.base },
			--       Pmenu = { bg = colors.mantle, fg = "" },
			--       PmenuSel = { bg = colors.surface0, fg = "" },
			--       CursorLineNr = { fg = colors.red },
			--       LineNr = { fg = colors.yellow },
			--       LineNrAbove = { fg = colors.surface1 },
			--       LineNrBelow = { fg = colors.surface1 },
			--       FloatBorder = { bg = colors.base, fg = colors.surface0 },
			--       VertSplit = { bg = colors.base, fg = colors.surface0 },
			--       WinSeparator = { bg = colors.base, fg = colors.surface0 },
			--       LspInfoBorder = { link = "FloatBorder" },
			--       YankHighlight = { bg = colors.surface2 },
			--       CmpItemMenu = { fg = colors.surface2 },
			--
			--       GitSignsChange = { fg = colors.peach },
			--
			--       NeoTreeDirectoryIcon = { fg = colors.subtext1 },
			--       NeoTreeDirectoryName = { fg = colors.subtext1 },
			--       NeoTreeFloatBorder = { link = "TelescopeResultsBorder" },
			--       NeoTreeGitConflict = { fg = colors.red },
			--       NeoTreeGitDeleted = { fg = colors.red },
			--       NeoTreeGitIgnored = { fg = colors.overlay0 },
			--       NeoTreeGitModified = { fg = colors.peach },
			--       NeoTreeGitStaged = { fg = colors.green },
			--       NeoTreeGitUnstaged = { fg = colors.red },
			--       NeoTreeGitUntracked = { fg = colors.green },
			--       NeoTreeIndent = { link = "IblIndent" },
			--       NeoTreeNormal = { bg = colors.mantle },
			--       NeoTreeNormalNC = { bg = colors.mantle },
			--       NeoTreeRootName = { fg = colors.subtext1, style = { "bold" } },
			--       NeoTreeTabActive = { fg = colors.text, bg = colors.mantle },
			--       NeoTreeTabInactive = { fg = colors.surface2, bg = colors.crust },
			--       NeoTreeTabSeparatorActive = { fg = colors.mantle, bg = colors.mantle },
			--       NeoTreeTabSeparatorInactive = { fg = colors.crust, bg = colors.crust },
			--       NeoTreeWinSeparator = { fg = colors.base, bg = colors.base },
			--
			--       TelescopePreviewBorder = { bg = colors.crust, fg = colors.crust },
			--       TelescopePreviewNormal = { bg = colors.crust },
			--       TelescopePreviewTitle = { fg = colors.crust, bg = colors.crust },
			--       TelescopePromptBorder = { bg = colors.surface0, fg = colors.surface0 },
			--       TelescopePromptCounter = { fg = colors.mauve, style = { "bold" } },
			--       TelescopePromptNormal = { bg = colors.surface0 },
			--       TelescopePromptPrefix = { bg = colors.surface0 },
			--       TelescopePromptTitle = { fg = colors.surface0, bg = colors.surface0 },
			--       TelescopeResultsBorder = { bg = colors.mantle, fg = colors.mantle },
			--       TelescopeResultsNormal = { bg = colors.mantle },
			--       TelescopeResultsTitle = { fg = colors.mantle, bg = colors.mantle },
			--       TelescopeSelection = { bg = colors.surface0 },
			--
			--       WhichKeyFloat = { bg = colors.mantle },
			--
			--       IblIndent = { fg = colors.surface0 },
			--       IblScope = { fg = colors.overlay0 },
			--
			--       MasonNormal = { bg = colors.mantle },
			--       MasonMutedBlock = { link = "CursorLine" },
			--
			--       LazyNormal = { bg = colors.mantle },
			--     }
			--   end,
			--   latte = function(colors)
			--     return {
			--       LineNr = { fg = colors.surface1 },
			--
			--       IblIndent = { fg = colors.mantle },
			--       IblScope = { fg = colors.surface1 },
			--     }
			--   end,
			-- },
		})
	end,
}
